### ISSUE TITLE
1-liner for Ubuntu 22.04

### ISSUE THREAD

**Issue by Utopiah** [FDH2/UxPlay#117]
When I saw the Debian warning in "Note to packagers" I incorrectly assumed no package for Ubuntu was available, as it's heavily relying on it. I then started to consider building from source but not after checking availability in repositories.

I had the good surprise to find it. Installing directly failed with `GStreamer error: Your GStreamer installation is missing a plug-in.` but using `sudo apt-get install uxplay gstreamer1.0-libav gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-gl` worked.

Thanks for the work!

**Comment by fduncanh** [comment]
Looks like Ubuntu-22.04 are providing OpenSSL-3 which satisfies Debian's license issues.
Debian has a package in "Sid" which should be in the next Debian release "bookworm".  Maybe that's where
the Ubuntu package is derived from?

Main changes since uxplay-1.46 are support for Raspberry Pi's GPU  using Gstreamer Video4Linux2.

**Comment by Utopiah** [comment]
Thanks for the clarification. Should I update the README.md to reflech that? Might help newcomers to not worry about the build process, which can be scary for some.

**Comment by fduncanh** [comment]
README is now updated!

Thanks
