### ISSUE TITLE
Dear develop, i want to ask you one question,Please 

### ISSUE THREAD

**Issue by nozuonodienobb** [FDH2/UxPlay#149]
i developing a app. can surport video push, but when switch  the videopush activity back to mirrorActivity, the i phone will give me setup    
post, open the mirror port again, but I can't get the correct H264 byte according to the previous image protocol. It can't be played after parsing, but it can be used for the first image. It can be switched back from the video push. Do you know why? please

**Comment by thiccaxe** [comment]
If I understand correctly, you seem to be using AirPlay 2. Airplay 2 is not fully documented, and poorly supported in open source software.

View out this repo for a Airplay2 implementation. https://github.com/alexfansz/AirplayServer-1/ 

You will find that for example, Spotify does not work. ALAC does not work because AirPlay 2 uses decoding modes and other flags not supported well by, essentially legacy open source implementation of ALAC

A similar issue might exist for how apple transports the video bytes.

Perhaps if you are able to share you source code, people can take a better look. Additionally, I am also interested in how you managed to get your 'videopush' feature to work well.

**Comment by nozuonodienobb** [comment]
3k your reply, i fix it, because i m not update the new streamId. i can‘t give your source code, but  I think we can communicate some problems in video push
