### ISSUE TITLE
Add a Homebrew Formula and WinGet

### ISSUE THREAD

**Issue by iMonZ** [FDH2/UxPlay#184]
Add Support for the Package Managing Systems:

macOS: https://docs.brew.sh/Formula-Cookbook https://docs.brew.sh/Adding-Software-to-Homebrew
Windows: https://learn.microsoft.com/en-us/windows/package-manager/package/

**Comment by fduncanh** [comment]
Feel free to provide a PR for this!  (but providing precompiled binary packages here would raise issues about GPL when linking to parts of Windows or MacOS that happens when one compiles, so  that has been avoided here so far by only distributing uncompiled code from this site, that users or distributions can compile.)

**Comment by iMonZ** [comment]
> Feel free to provide a PR for this! (but providing precompiled binary packages here would raise issues about GPL when linking to parts of Windows or MacOS that happens when one compiles, so that has been avoided here so far by only distributing uncompiled code from this site, that users or distributions can compile.)

So for macOS you don’t provide the binary. You just create the formula for how to compile it. And the file is going to be compiled on the end user device.

**Comment by fduncanh** [comment]
formula would be just be a translation into the right format of something like

```
brew install pkgconfig cmake libplist opensll
brew install gst-plugins-base gst-plugins-good gst-plugins-bad gst-libav
export GST_PLUGIN_PATH=/usr/local/lib/gstreamer-1.0     (maybe not needed)
(get/unpack source)
cd UxPlay
cmake . 
make 
sudo make install 
(some kind of cleanup/registration with homebrew  for uninstallation, etc.)
```

**Comment by fduncanh** [comment]
If you can make a start on a  home brew formula, I will understand what its trying to do and tweak it or give guidance.

**Comment by fduncanh** [comment]
@iMonZ  I created and tested working homebrew formula, and tested it on macOS Catalina  (which Homebrew doesn't like anymore because its too old)

* This UxPlay site does all the development, but is technically a fork of the antimof UxPlay site.  brew audit rejects the formula because 

```
* GitHub fork (not canonical repository)
```
whether the Homebrew maintainers could/would grant an exception is unclear.

* their documentation says "We frown on authors submitting their own work unless it is very popular."

so it's up to you to get the formula into Homebrew.   Here it is [uxplay.rb.txt](https://github.com/FDH2/UxPlay/files/10847431/uxplay.rb.txt)

**Comment by iMonZ** [comment]
Thanks!
