### ISSUE TITLE
Add extra dependency

### ISSUE THREAD

**Issue by Koefte** [FDH2/UxPlay#281]
How do i add an additional dependency to uxplay?

**Comment by fduncanh** [comment]
Please explain

**Comment by Koefte** [comment]
> Please explain

I am trying to include SDL in uxplay code for visualization purposes and I don't know how and where to link to sdl

**Comment by thiccaxe** [comment]
What are you trying to do? End goal?

**Comment by Koefte** [comment]
Wrap uxplay around a graphic environment

**Comment by thiccaxe** [comment]
You could customize the gstreamer arguments and see if you can pipe that into your program.

**Comment by Koefte** [comment]
> You could customize the gstreamer arguments and see if you can pipe that into your program.   

Please elaborate

**Comment by fduncanh** [comment]
cmake is used for dependencies.   see the three CMakeLists.txt files.

what exactly do you want do?  give uxplay a gui front end?   replace gstreamer as the renderer? both?

**Comment by Koefte** [comment]
Give uxplay a gui front end

**Comment by fduncanh** [comment]
I held off on doing that that because right now,  uxplay works on all sorts of systems , from linux to macos to *BSD to windows to Raspberry Pi Lite.      Certainly an option to build a gui front end could be good, but the choice should be cross-platform

On Linux there are gtk or qt as gui possibilities.

But Uxplay doesn't accept any input (except from the client) after it starts, so its not clear that the gui would do more than "prettify" things
