### ISSUE TITLE
Progress in adding support for HLS video streaming (YouTube, maybe NetFlix)

### ISSUE THREAD

**Issue by fduncanh** [FDH2/UxPlay#315]
see the end of the long issue thread #134

Help with this would be appreciated:

1. "Almost implemented" :needs debugging  + a videoplayer backend
 
2.  There is a working open source "demo"  that output can be compared to.

**Comment by AndrewPochapsky** [comment]
Sorry for the potentially dumb question, but will this feature allow streaming video from youtube directly using airplay instead of using screen mirroring? I am very interested in this feature though I don't really have the c skills to meaningfully contribute. Also just found this project, thank you so much for what you do.

**Comment by fduncanh** [comment]
Yes, this is for streaming video (Youtube/netflix, etc)
