### ISSUE TITLE
Big latency / lag observed after uxplay runs for an extended period of time

### ISSUE THREAD

**Issue by carylewis** [FDH2/UxPlay#376]
I am running uxplay on a Raspberry Pi 5, like this:

`/usr/local/bin/uxplay -vs videoconvert ! video/x-raw,width=400,height=768 ! ximagesink display=:1 -d -nh -n 000  -m d8:3a:dd:4f:e8:61`

If I leave it running while an iPhone is connected for an extended period of time, there is a big latency between when a change happens on the iPhone, such as swiping left and right through the app tab, and seeing the change in the uxplay screen.

When first run, there is no latency / lag.

Has anyone else seen this?

Is this expected behaviour?

I will attempt to identify any memory leaks in the app, and I am capturing the debug log, but I didn't see anything in the logs that jumped out at me.

**Comment by fduncanh** [comment]
can you explain 
>/usr/local/bin/uxplay -vs videoconvert ! video/x-raw,width=400,height=768 ! ximagesink display=:1 -d -nh -n 000  -m d8:3a:dd:4f:e8:61

are there quotes ("...") missing in your command line quoted above?

which OS ( R Pi OS bookworm?)

**Comment by carylewis** [comment]
Raspberry Pi, Raspberry PI OS - debian - bookworm

This is the full command (the original post had a copy / paste of a ps command)

`stdbuf -o0 -e0 /usr/local/bin/uxplay  -vs "videoconvert ! video/x-raw,width=400,height=768 ! ximagesink display=:1" -d -nh -n "000" -m d8:3a:dd:4f:e8:61 2>&1 | tee -a /home/pi/.vnc/$(hostname):1.log |stdbuf -o0 -e0 grep -i erro`

This command runs in the context of a tigergnc virtual X session.

What I observe is that after uxplay has been running for a number of hours, there is an almost 2 second delay from when I swipe left to when the uxplay app displays the changes.

Once uxplay is restarted, within the same tigervnc session, the delay disappears.

**Comment by fduncanh** [comment]
if you are running uxlpay to mirror a display rather than watch a video, maybe switch off video synchronization with the NTP time signal from the client.


try "uxplay -vsync no"  see if that helps.

the README says
https://github.com/FDH2/UxPlay#starting-and-running-uxplay

In Mirror mode, GStreamer has a choice of two methods to play video with its accompanying audio: prior to UxPlay-1.64, the video and audio streams were both played as soon as possible after they arrived (the GStreamer "sync=false" method), with a GStreamer internal clock used to try to keep them synchronized. Starting with UxPlay-1.64, the other method (GStreamer's "sync=true" mode), which uses timestamps in the audio and video streams sent by the client, is the new default. On low-decoding-power UxPlay hosts (such as Raspberry Pi Zero W or 3 B+ models) this will drop video frames that cannot be decoded in time to play with the audio, making the video jerky, but still synchronized.

**Comment by carylewis** [comment]
Thanks for pointing that out, I will run some tests with "-vsync no".

I'm still trying to understand why a lag builds up over time.

If you have any suggestions as to what I should attempt to capture in the logs, I'm happy to run some experiments. I will try to take a movie of the vnc session along side the physical phone to demonstrate the lag.

**Comment by carylewis** [comment]
"-vsync no" helped, I no longer experience a lag after running uxplay for extended periods of time. Thanks for the tip.
