### ISSUE TITLE
ios9 mirror 【*** ERROR decryption of video packet failed  】

### ISSUE THREAD

**Issue by hushilin** [FDH2/UxPlay#40]
ios9 mirror error。 ios10 OK

**Comment by hushilin** [comment]
Macos openssl3.0.0出现错误，更换openssl1.1.1 已经好了

**Comment by fduncanh** [comment]
This is a new feature in the code, which I may have to change.   Please post exactly which version of UxPlay you are using, and the debug output of uxplay -d.    (up to the ERROR)

Do both audio and video fail?

I need to know what ios9 reports as its "sourceVersion"  this is seen in the debug output

**Comment by hushilin** [comment]
控制台部分日志：
```
raop_rtp_mirror accepting client
raop_rtp_mirror width_source = 304.000000 height_source = 540.000000 width = 318.000000 height = 564.000000
raop_rtp_mirror sps size = 20
raop_rtp_mirror pps size = 4
raop_rtp_mirror video ntp = 1639552615214109, now = 1639552615159764, latency = -54345
*** ERROR decryption of video packet failed 
```
#define VERSION "1.44" 
@fduncanh

**Comment by hushilin** [comment]
It may be a problem with the openssl version

**Comment by fduncanh** [comment]
NO its not that.

Is  this a complete failure or just a single event.

What happens when you run uxplay -d with ios 9

**Comment by hushilin** [comment]
> 
`erbao:Debug admin$ ./uxplay -d
using system MAC address ac:de:48:00:11:22
Initialized server socket(s)
raop port =  51458
Accepted IPv4 client on socket 28
Local: 192.168.0.199
Remote: 192.168.0.112
Open connections: 1
client sourceVersion 260.26 (no hash of aeskey if <= 280.33)
raop_rtp_mirror starting mirroring
Accepted IPv4 client on socket 32
Local: 192.168.0.199
Remote: 192.168.0.112
Open connections: 2
*** ERROR decryption of video packet failed `

**Comment by fduncanh** [comment]
run ```uxplay -d```

then
```uxplay -d > filename  2>&1```

to send debug output to the file ``filename```
 
It will tell you if all video ((and audiio) fails decryption.
or  just one frame.

**Comment by hushilin** [comment]
> 

@fduncanh 
`erbao:Debug admin$ ./uxplay -d
using system MAC address ac:de:48:00:11:22
Initialized server socket(s)
raop port =  51458
Accepted IPv4 client on socket 28
Local: 192.168.0.199
Remote: 192.168.0.112
Open connections: 1
client sourceVersion 260.26 (no hash of aeskey if <= 280.33)
raop_rtp_mirror starting mirroring
Accepted IPv4 client on socket 32
Local: 192.168.0.199
Remote: 192.168.0.112
Open connections: 2
*** ERROR decryption of video packet failed `

**Comment by fduncanh** [comment]
Yes I see.    (but some how the -d option  is not giving the full debug output for you)

ios9  sourceVersion 260.26 is the issue.       I will fix the new code right now.

**Comment by fduncanh** [comment]
Thank you for reporting this.   Its a change I just made yesterday.

**Comment by hushilin** [comment]
> 
[未命名.txt](https://github.com/FDH2/UxPlay/files/7717314/default.txt)

**Comment by hushilin** [comment]
Is this a problem with the video renderer, or an airplay protocol error?

**Comment by fduncanh** [comment]
No it is a special protocol change to accomodate a Windows Client AirMyPC that uses an older protocol.
see issue #37 

This works with a true Apple TV and declares sourceVersion 280.33.

I had assumed that the AppleTV recognizes 280.33 as too old for the modern protocol, and uses the old one for clients with 280.33 or earlier.     Clearly I was wrong since it seems iOS9 (250.26) uses the new protocol
I will detect AirMyPC a different way, and use the old  protocol  only for AirMyPc.

I guess iOS10 has a sourceVersion greater than 280.33

**Comment by hushilin** [comment]
> 

IOS10 : client sourceVersion 320.20 (no hash of aeskey if <= 280.33)
IOS14:  client sourceVersion 540.31 (no hash of aeskey if <= 280.33)

**Comment by fduncanh** [comment]
Your debug output  confirms what guessed.

Thank you

UxPlay 1.43 should work for you (see releases) till I fix 1.44 (not yet a release)

**Comment by fduncanh** [comment]
I dont know what AppleTV is using to know that AirMyPc uses the old protocol if it is not using sourceVersion....


Please check that UxPlay 1.43 works with ios9

**Comment by hushilin** [comment]
> 

You are so hard！
Which country are you from？

**Comment by fduncanh** [comment]
planet earth

**Comment by hushilin** [comment]
> 

nice!。
1.4.3 支持 iOS 9

**Comment by hushilin** [comment]
The mirroring connection is successful, why is there no sound?

**Comment by fduncanh** [comment]
No sound with 1.43  and ios9

was there sound but no video with 1.44?

**Comment by fduncanh** [comment]
In modern iOS AESkey is hashed with ecdh_secret 

It is then used fro both sound an (in a complicated way) for video.
AirMyPC uses unhashed AESkey for both.
  its possible ios9 used hashed for video and unhashed for sound (?)

both are hashed in  1.43
 none are hashed in 1.44 that you have, for sourceVersion < 280.33
.

**Comment by hushilin** [comment]
> 1.43 和 ios9 没有声音
> 
> 1.44 有声音但没有视频吗？

1.43  - iOS9, iOS10 都没有声音
Error ： *** ERROR decryption of audio (compression_type 8) failed

**Comment by hushilin** [comment]
No sound is just an GStreamer audio renderer problem,
Isn't it the problem in the airplaylib protocol code?

Because I only need the code in airplaylib to parse with ffmpeg

**Comment by fduncanh** [comment]
If you get that *** ERROR message  for audio, it means that the AES decryption of the audio stream failed.
if you get the  *** ERROR for video. it means that decryption of the video stream failed.

(These are two separate decryption processes).       
The Error is detected by examining the audio or video stream just before giving it the the GStreamer renderer, but
happens earlier in the decrypt process   (raop_buffer.c (audio), mirror_buffer.c (video) in lib)

0.  client and  seen in  create a "shared" secret ecdh_secret
1. (client) sends ekey (72 bytes)  and eiv (16 bytes))to server
2.   server uses reverse-engineered FairPlair description (playfair) to extract  aeskey from  ekey
3,    aeskey + ecdh_secret  -> sha512 hash ->  (decrypted) aeskey   

(aeskey, eiv) are the (key,iv) pair for audio AES-CBC decryption
 AES CTR decryption uses a (key, iv) pair derived from aeskey and streamConnectionID.

old protocol (seen in Windows emulator AirMyPc)  : omit step 3.
Airplay 1 audio (audio only) omits step 3.
really old ios  (5 maybe) did not encrypt  screen mirror video.
 


1.43 and 1.44 should behave identically for iOS 10 and later.
do audio and video both work for you in ios14?

which  iOS versions do you think should be supported?

I am supporting  the old protocol for AirMyPC because it is currently used and a teacher wants if for a class
where some students have iPads, other have some Windows surface which can run AirMyPC.

**Comment by fduncanh** [comment]
The failure of video decryption is detected in raop_rtp_mirror.c  (look for "nalu")
and is marked by setting the first byte of the video frame to 0x1.

For audio (raop_rtp.c)  the code where the decryption takes place doesnt know it the audio is ALAC or AAC (but could test for both, I suppose)    .  Because of this, testing for bad decryption was postponed till gstreamer, which has been told what  audio format to expect.

bad decryption was never seen before a user tried to make uxplay work with the AirMyPC client.
its only detected since 1.43

Maybe no-one reported failures with old iOS versions.

**Comment by fduncanh** [comment]
@hushilin 
please test with latest version of 1.44

You can try to get audio on ios9 ios10 to decrypt properly by adding their User-Agent strings in lib/global.h

replace   OLD_PROTOCOL_AUDIO_CLIENT_LIST "AirMyPC/2.0;xxxx"
by  OLD_PROTOCOL_AUDIO_CLIENT_LIST "AirMyPc/2.0;AirPlay/260.26;AirPlay/320.20;xxxx"

for both iOS 9 and  iOS10 clients you are testing.

**Comment by hushilin** [comment]
> @hushilin please test with latest version of 1.44
> 
> You can try to get audio on ios9 ios10 to decrypt properly by adding their User-Agent strings in lib/global.h
> 
> replace OLD_PROTOCOL_AUDIO_CLIENT_LIST "AirMyPC/2.0;xxxx" by OLD_PROTOCOL_AUDIO_CLIENT_LIST "AirMyPc/2.0;AirPlay/260.26;AirPlay/320.20;xxxx"
> 
> for both iOS 9 and iOS10 clients you are testing.

You modified version 1.4.4. I tested ios9 and 10 and there is still no sound.

**Comment by fduncanh** [comment]
Please try with a new version  of 1.44  I just committed

Thank you

**Comment by hushilin** [comment]
Just modify  lib/global.h `OLD_PROTOCOL_AUDIO_CLIENT_LIST "AirMyPc/2.0;AirPlay/260.26;AirPlay/320.20;xxxx"`  ？？？

After I modified it myself, compiled it
 I tested ios9 and 10 and there is still no sound.

**Comment by fduncanh** [comment]
This probably means that UxPlay and RPiPlay have never supported ios9 and ios10 audio...

Please test with http://github.com/FD-/RPiPlay     to make sure  that it is not something I have broken.

I will see what I can learn about the history of these iOS versions

**Comment by fduncanh** [comment]
I dont' see any reference to anything older than  iOS 12.4 in the history on the RPiPlay site, so my guess is  RPiPlay won't work with iOS 9 and 10.     (But perhaps only some small change in protocol might be need to be guessed)

**Comment by hushilin** [comment]
uxplay Is it modified from [AirplayServer](https://github.com/KqSMea8/AirplayServer)?

I only need to be able to connect to IOS devices, I can use it directly  [AirplayServer](https://github.com/KqSMea8/AirplayServer) lib cpp code?？

**Comment by hushilin** [comment]
Want to ask you `void video_process (void *cls, raop_ntp_t *ntp, h264_decode_struct *data) `  in `h264_decode_struct` is the data returned in standard H264 format ？ 

I want to use the iOS` VideoToolbox.h` library `CMVideoFormatDescriptionCreateFromH264ParameterSets` to parse the data, but it fails

**Comment by fduncanh** [comment]
Did you test RPiPlay?

The history is  shairplay -> AirPlayServer ( by dsafa22 , in java for Android, but contains C from modified shairplay) -> RPiPlay -> UxPlay

For AirServer details see dsafa22's  discussion paper https://github.com/FDH2/UxPlay/wiki/AirPlay2

he explored with  iOS 12.0.1   User-Agent: AirPlay/371.4.7   so wont help for iOs 9 and 10.

However the fact the video is working makes it possible that  the audio setup is simpler  that the one in RPiPlay, but more complex than that in shairplay.    The audio in the AirMyPC app is the same as in shairplay.

**Comment by fduncanh** [comment]
Video data is not quite pure h264.   see what happens after the decryption in raop_rpt_mirror.c   (look for nalu)

The decrypted data is converted back to pure h264 there.  See  dsafa22's paper.

**Comment by fduncanh** [comment]
void video_process (void *cls, raop_ntp_t *ntp, h264_decode_struct *data)


 The data here has already been converted to pure h264.

**Comment by hushilin** [comment]
When I first call `void video_process (void *cls, raop_ntp_t *ntp, h264_decode_struct *data)` data.length == 30 I want to get` nalu sps pps`

I found an example elsewhere. The data returned by first call, data.length is 36 or 37, can be decoded successfully with VideoToolbox.h

That’s why I asked you whether the returned standard 264 data

**Comment by hushilin** [comment]
[Ios AirplayMirror](https://github.com/openairplay/AirplayMirror)  he did not provide the source code

`[void airplay_data_receive(unsigned char* buffer, long buflen, int payload,void* ref)](https://github.com/openairplay/AirplayMirror/blob/master/PlayTest/ViewController.mm)`  data.length is 36 or 37, can be decoded successfully with VideoToolbox.h

i'm not very familiar with C language code, can you help me see it?

**Comment by hushilin** [comment]
> 

libairplaymirror.a  The static library has serious bugs  ，Uncertain collapse

**Comment by fduncanh** [comment]
good find ! 
Its written in Objective C (Apple language) not C though.


maybe the audio decryption protocol for iOS 9,10 11 is in there somewhere
I now think UxPlay as written is for ios 12 and later   note that (from RPiPlay notes)

```
For iOS 9, Apple made considerable changes to the AirPlay protocol in 2015, including audio and mirroring. Apparently, the audio protocol was only slightly modified, and a minor change restored compatibility. For mirroring, an additional pairing phase was added to the connection establishment procedure, consisting of pair-setup and pair-verify calls. Seemingly, these were added in order to simplify usage with devices that are connected frequently. Pair-setup is used only the first time an iOS device connects to an AirPlay receiver. The generated cryptographic binding can be used for pair-verify in later sessions. Additionally, the stream / stream.xml endpoint was replaced with the info endpoint (only available as binary plist AFAICT). As of iOS 12, the protocol introduced with iOS 9 was still supported with only slight modifications, albeit as a legacy mode. While iOS 9 used two SETUP calls (one for general connection and mirroring video, and one for audio), iOS 12 legacy mode uses 3 SETUP calls (one for general connection (timing and events), one for mirroring video, one for audio).
```
.

**Comment by fduncanh** [comment]
I'll look some more at your 
uxplay -d output for ios9
 can you post the same for ios10?

**Comment by hushilin** [comment]
> 
The internal implementation of `libairplaymirror.a` should be implemented in C language. Object-C just calls it. But the source code of `libairplaymirror.a` is not provided

I want you to help me reason about why it calls data.length for the first time is 36.

**Comment by fduncanh** [comment]
} else if ((payload_type & 255) == 1) {
                // The information in the payload contains an SPS and a PPS NAL
line 355 raop_rtp_mirror.c

**Comment by fduncanh** [comment]
// The sps_pps is not encrypted

**Comment by fduncanh** [comment]
// Copy the sps and pps into a buffer to hand to the decoder

**Comment by fduncanh** [comment]
If you post the output (with working video, but broken audio of newest uxplay -d

for both ios9 and ios10 
I might now see why audio didnt work,

**Comment by hushilin** [comment]
thank you very much 
The ios hard decoding succeeded.

**Comment by hushilin** [comment]
> 



> 如果您发布输出（伴随工作视频，但最新的 uxplay -d 的音频已损坏）
> 
> 对于 ios9 和 ios10， 我现在可能已经明白了原因了，

do you still need uxplay iOS10 running log information?

**Comment by hushilin** [comment]
there is no sound in iOS9,10  is there no way to solve this problem?

**Comment by fduncanh** [comment]
Please post the full debug logs for both  iOS9 and 10. (with working video)

Maybe I can see what goes wrong with sound (but maybe not)

The current support is ios12 or later.

**Comment by hushilin** [comment]
> 

You haven't slept yet?

This is the debug log：
[ios9_log.txt](https://github.com/FDH2/UxPlay/files/7728209/ios9_log.txt)
[ios10_log.txt](https://github.com/FDH2/UxPlay/files/7728211/ios10_log.txt)

**Comment by fduncanh** [comment]
Interesting.
These debug logs are using the "old protocol for audio (the unhashed AES key for audio)
and most of the  audio  frames seem to be correctly decrypted, just some fail.  I see 8 good frames then 1 bad one in the debug.

I ask why no audio was heard, since most audio frames seem to be good.    Maybe the volume is turned off?
There is some negotiation about volume between client and server.
---------------------------------------------------------
I now removed the "old protocol" for lib/global.h

can you repeat the test again with a new download of uxplay (or just  edit global.h so it says

```
#define OLD_PROTOCOL_AUDIO_CLIENT_LIST "AirMyPC/2.0;xxx"
#define OLD_PROTOCOL_VIDEO_CLIENT_LIST "AirMyPC/2.0;xxx"
```
Or try with 1.42.

I would then expect to see EVERY audio frame fail.   does that happen?

**Comment by hushilin** [comment]
new [ios10_log.txt](https://github.com/FDH2/UxPlay/files/7731999/ios10_log.txt)

@fduncanh 
In addition, I would like to ask, is the video projection data played on the web page different from the screen mirroring data?

Screen mirroring can display, video projection screen displays black

**Comment by fduncanh** [comment]
@hushilin 
This in ios10_log.txt  I think means that you are still running the previous code, not the one I need to test.

```
Client identified as User-Agent: AirPlay/320.20
This identifies client as using old protocol for AES audio key)
timing_rport = 59450
raop_ntp parse remote ip = 169.254.149.55
````

Please make sure that lib/ global.h in the test looks like.
```
#ifndef GLOBAL_H
#define GLOBAL_H

#define GLOBAL_FEATURES 0x7
#define GLOBAL_MODEL    "AppleTV2,1"
#define GLOBAL_VERSION  "220.68"

/* use old protocol  for AES key if User-Agent string is contained in these strings */
/* replace xxx by any new User-Agent string as needed */
#define OLD_PROTOCOL_AUDIO_CLIENT_LIST "AirMyPC/2.0;xxx"
#define OLD_PROTOCOL_VIDEO_CLIENT_LIST "AirMyPC/2.0;xxx"

#define MAX_HWADDR_LEN 6

#endif
```
```
The code has line 405 in lib/raop_handlers.h
which  should not produce the output I am seeing in your output if global.h is like the one above.

```
        const char * user_agent = http_request_get_header(request, "User-Agent");
        logger_log(conn->raop->logger, LOGGER_INFO, "Client identified as User-Agent: %s", user_agent);	
        unsigned char *aeskey_audio, *aeskey_video;
            if (strstr(OLD_PROTOCOL_AUDIO_CLIENT_LIST,user_agent)) {   /* old-protocol clients use the unhashed AES key */
            logger_log(conn->raop->logger, LOGGER_INFO, "This identifies client as using old protocol for AES audio key)");
            aeskey_audio = aeskey_old;
        } else {
            aeskey_audio = aeskey;
        }
```

**Comment by fduncanh** [comment]
video project:

Yes uxplay does not have the webserver mode that apple tv has, where video streamer from a site to the ipad/iphone is streamed directly to the AppleTV.

**Comment by hushilin** [comment]
> 
[ios_10.txt](https://github.com/FDH2/UxPlay/files/7735591/ios_10.txt)
sorry! 
This is the latest version of the log

**Comment by fduncanh** [comment]
Thank you!

Yes this time it used the hashed AES KEY (not the unhashed one) for audio, but looks just the same 
as with the unhashed key,  both seem bad.    I need to make the debug mode to show more details
about the audio decryption  directly  (inside raop_rtp.c) rather than wait till the audio stream gets to gstreamer.

This will be to count how many successful decrypted audio frames there are (if any) before a bad one, and print the beginning of the bad frame.
 
I'll  post here when this is ready to be tried, if it is not too much trouble for you (I dont have access to the old hardware)    If there is an easy fix, it would be nice to support those old 32-bit iPads etc that are stuck at iOS9.3 .    I was surprised that I could guess an easy fix that worked  for the old-protocol  Windows  AirPlay-client emulator AirMyPc,  that someone wanted to use.

(It is not high priority, as I  don't know if  anyone will actually use ios9 devices if it gets fixed, at least the video works which is OK for some uses).

Why are you using ios9 , ios10 devices?

**Comment by fduncanh** [comment]
@hushilin 
Thanks for you help.

Get a fresh download of uxplay-1.44 and edit lib/glocal.h

Change  ```#define DECRYPTION_TEST 0``` to ```#define DECRYPTION_TEST 1``` and build.

Run "uxplay"  (WITHOUT -d option) with and iOS 9 or iOS10 client streaming audio as well as video.

Then again edit global.h to replace
```#define OLD_PROTOCOL_AUDIO_CLIENT_LIST "AirMyPC/2.0;xxx"``` by
```#define OLD_PROTOCOL_AUDIO_CLIENT_LIST "AirMyPC/2.0;AirPlay/260.26;AirPlay/320.20;xxx"```

and run it again with an iOS9 or iOS10 client, streaming audio as well as video.

When run with a working client, you will see output like
```
AirMyPC/2.0;xxx
273 before ef 8c 8a 2d 8d 18 f0 68 83 6c 3f c5 ad 28 53 3f 
273 after   8e 81 b2 d4 d8 a8 10 2b 7a 95 c8 16 a3 4e fc ae 

AirMyPC/2.0;xxx
265 before 23 2d 24 87 55 36 ac 8c f4 a3 5d 30 af b4 13 b3 
265 after   8e 83 b4 51 e0 ec 74 08 14 47 30 a9 08 04 5b 55 

AirMyPC/2.0;xxx
283 before d8 ea 65 c2 d6 69 04 36 2a a7 63 63 a9 b6 bd 55 
283 after  8d 06 eb df ef f0 96 a8 73 14 c2 05 5c a8 73 55 
```

**Comment by hushilin** [comment]
> 

@fduncanh 

```
start audio connection, format AAC-ELD 44100/2
raop_rtp starting audio
AirMyPC/2.0;AirPlay/260.26;AirPlay/320.20;xxx
44 before c2 00 0c 17 eb 5e 9c 75 4b 82 73 5c c0 9f d1 11 
***ERROR AUDIO FRAME  IS NOT AAC_ELD OR ALAC
44 after  81 c0 00 00 00 7c 83 86 4f 25 2d c3 cc a3 c0 3e 

*** ERROR decryption of audio frame (compression_type 8) failed 
AirMyPC/2.0;AirPlay/260.26;AirPlay/320.20;xxx
132 before e9 c8 f8 83 8f ea 4e 90 53 0b 58 02 c1 6a c1 f3 
***ERROR AUDIO FRAME  IS NOT AAC_ELD OR ALAC
132 after  82 92 a9 b1 d0 60 33 ab d7 1c f5 86 10 99 df 43 

AirMyPC/2.0;AirPlay/260.26;AirPlay/320.20;xxx
124 before 3d 5a 46 83 a3 ab 02 ed df 10 9c 46 11 a0 24 68 
***ERROR AUDIO FRAME  IS NOT AAC_ELD OR ALAC
124 after  82 94 a7 42 50 c0 34 79 6e 19 d2 98 a8 c8 1d 29 

AirMyPC/2.0;AirPlay/260.26;AirPlay/320.20;xxx
100 before d6 02 76 ac b4 70 5f f6 e0 09 f7 a6 12 bd 41 51 
***ERROR AUDIO FRAME  IS NOT AAC_ELD OR ALAC
100 after  82 98 a2 b2 e0 88 90 19 ec d8 72 ce 19 7c 6d 98 

AirMyPC/2.0;AirPlay/260.26;AirPlay/320.20;xxx
100 before 62 d4 6b 44 df 3c e8 8a 5d 9a d0 b7 fb 28 95 e5 
***ERROR AUDIO FRAME  IS NOT AAC_ELD OR ALAC
100 after  82 94 a5 b2 51 20 35 75 a4 f4 13 19 cc 35 56 d0 

AirMyPC/2.0;AirPlay/260.26;AirPlay/320.20;xxx
88 before ef 88 c4 f1 e7 a8 5c 59 30 47 87 71 9c a0 3d 2e 
***ERROR AUDIO FRAME  IS NOT AAC_ELD OR ALAC
88 after  82 9c 87 23 04 60 37 d1 1e 9e 5a c4 f4 dc 34 d1 

AirMyPC/2.0;AirPlay/260.26;AirPlay/320.20;xxx
96 before 08 bc 81 5f e1 97 93 93 89 0c 72 66 6d 02 9a 54 
***ERROR AUDIO FRAME  IS NOT AAC_ELD OR ALAC
96 after  82 98 a4 34 08 a0 33 da f0 f5 37 79 f4 c6 d1 8b 

```

**Comment by fduncanh** [comment]
AHA!  first byte is always 81 or 82 after decryption!    (not random   so the decryption is successful!)
So it is decrypted with the old protocol, but is not AAC-ELD audio!
Probably AAC-LD  (which AIrPlay also supports)

**Comment by fduncanh** [comment]
@hushilin 
I am hoping that the AAC-ELD audio will work now.

Please download a new copy of 1.44,  build and test it.  (just use "uxplay").
If it works, please test both iOS9 and iOS10, and let me know the precise iOS versions on your two iPhones.
(Probably the last ones that work for those models?).



If the sound still does not work, please edit global.h to  
change ```#define DECRYPTION_TEST 0``` to ```#define DECRYPTION_TEST 2``` and rebuild.

This will output complete decrypted audio frames.
Please post output with  about 10 frames here, I will try to find out what GStreamer settings are needed to play them.
(the frames begin with  0x81 or 0x82 rather than 0x8d and 0x8e from modern iOS.)

**Comment by fduncanh** [comment]
@hushilin 

If you have time, please check if sound is working now ....

**Comment by fduncanh** [comment]
now tested on iPhone 4,1  ios9 running iOS 9.3.6 (User  Agent: AirPlay/280.33)
(most recent iOS for 32bit device)

Protocol is same as current   (hashed audio AES key) , but first byte of AAC-ELD audio frames is 0x81 or 0x82, while modern 64 bit iOS devices have AAC-ELD  audio frames starting 0x8d or 0x8e.
