### ISSUE TITLE
build fails on debian 11

### ISSUE THREAD

**Issue by velvetant** [FDH2/UxPlay#61]
hi,

probably a really simple thing but after some hours I give up. not experienced enough in compiling. 

error is: 
```
user@buildpc:~/Downloads/UxPlay/build$ make
[ 18%] Built target playfair
[ 30%] Built target llhttp
[ 84%] Built target airplay
[ 93%] Built target renderers
[ 96%] Linking CXX executable uxplay
/usr/bin/ld: lib/playfair/libplayfair.a(modified_md5.c.o): undefined reference to symbol 'sin@@GLIBC_2.2.5'
/usr/bin/ld: /lib/x86_64-linux-gnu/libm.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/uxplay.dir/build.make:118: uxplay] Error 1
make[1]: *** [CMakeFiles/Makefile2:209: CMakeFiles/uxplay.dir/all] Error 2
make: *** [Makefile:149: all] Error 2
```

I've tried adding `-lm` in several places as that seems to be the way to solve this according to google.

Also tried git version and release 1.46.

Dependencies are all standard from the bullseye repositories. All needed deps should be installed.

Thanks in advance!

**Comment by fduncanh** [comment]
just (re)tested on current debian 11 Bullseye :  the build of current git version  works and runs  (on intel x86_64 architecture)

compiler was  g++
 gcc version 10.2.1 20210110 (Debian 10.2.1-6) 

I'm guessing your compiler isnt properly installed (?)

what does "sudo apt-get install g++" do for you?
for me it gives
```
g++ is already the newest version (4:10.2.1-1).
```

start again with a clean github download, and don't change anything (no -lm ...) etc, because uxplay is confirmed to build on bullseye (at  least on x86_64).   (Of course if you are building on arm raspberry pi 4, I can't test to see if something is broken there)

**Comment by fduncanh** [comment]
not a uxplay issue.   needs to check compiuler installation  (use g++)

**Comment by velvetant** [comment]
As it happens so often a reboot after ```sudo apt-get purge g++ gcc``` + then a reinstallation + a fresh `git clone` fixed it - thanks!
