### ISSUE TITLE
not sure how to debug avahi

### ISSUE THREAD

**Issue by qrkourier** [FDH2/UxPlay#79]
Symptom of the problem: run uxplay on Linux and wait a long time for it to appear in screen mirroring list of AirPlay servers. Sometimes it appears and disappears for no apparent reason. Sometimes when it appears and I tap it then uxplay's verbose messages don't show any activity, as though it's not beginning to connect at all.

Things I've tried:
* building HEAD of main branch to stay up to date
* restarting avahi-daemin
* toggling airplane mode on iPad to reset networking
* toggling WiFi on laptop to trigger networking hard fail and reset
* repositioning iPad and laptop in case of poor signal

It did seem to help when I repositioned the antennae and so I suspect a poor signal could play a part, and that's obviously outside the scope of this repo. :slightly_smiling_face: 

I just don't know much yet about how uxplay uses avahi to advertise itself so I'm wondering what to look for in avahi logs or uxplay logs to see a clue about the advertising success or failure that might point me toward the root cause. 

Thank you for any insights!

**Comment by fduncanh** [comment]
@qrkourier 
I had issues with avahi for a long time but they are now fixed.  (I'm not quite sure what I did to fix them)

*  I needed to have the client looking for the server BEFORE Uxplay was run, in order for the client to see it.   And  if the connection was stopped, one couldnt reconnect the client after about 5 mins of inactivity.
 there is a -t n option for restarting the server after a timeout period n secs  of inactivity that I added to mitigate this, but the problem is just a misconfigured  network, and doesnt need that uxplay option (which I should remove).

The tool avahi-browse  (`avahi-browse --all`) should be installed (it's in avahi-utils) and can help see what is going on.

I wish I could tell you what to do, but after intermittent tinkering, one day it was working perfectly, and the "-t n" option I added was unnecessary.     Most users dont seem to have these issues, I think it was my local network setup.    (I have dns-masq providing nameserver services on the router, not a simple ".local"  mdns setup.) Some extra configuration was necessary.

**Comment by fduncanh** [comment]
The magic is called DNS-SD   ("service discovery")


https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwiZisnKnMb2AhXdlYkEHbCFDXIQFnoECAkQAQ&url=http%3A%2F%2Fwww.dns-sd.org%2F&usg=AOvVaw2mnUXh_e2Ad09mg1JYe9Y8DNS-SD           

https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwiZisnKnMb2AhXdlYkEHbCFDXIQFnoECAoQAQ&url=https%3A%2F%2Fwww.win.tue.nl%2F~johanl%2Feduc%2FIoT-Course%2FmDNS-SD%2520Tutorial.pdf&usg=AOvVaw2xn_n28i-kl-DQpmRzkWqJ

https://stevessmarthomeguide.com/multicast-dns/
